name: Release CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release: major|minor|patch'
        required: true
        default: patch

jobs:
  release:
    runs-on: ubuntu-latest
    name: release

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:12.21-npm6
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
    - name: Checkout
      uses: actions/checkout@ee5a9d1395988d7c82c67c69571871f5994b94df # pin@v2
      with:
        fetch-depth: 0
        ref: master

    - name: Cache node modules
      uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
      with:
        path: |
          .npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
      continue-on-error: true

    - name: Install dependencies
      run: npm install --no-audit

    - name: git config
      run: |
        git config user.name $GIT_USER
        git config user.email $GIT_EMAIL
        mkdir -p ~/.gnupg/
        printf $GPG_KEY | base64 -d > ~/.gnupg/private.key
        gpg --import ~/.gnupg/private.key
        git config commit.gpgsign true
        git config user.signingkey $GIT_SIGNING_KEY
      env:
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GIT_SIGNING_KEY: ${{ secrets.GIT_SIGNING_KEY }}

    - name: npm config
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Release ${{ github.event.inputs.version }}
      run: |
        git reset --hard
        npm run release:${{ github.event.inputs.version }} --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GIT_SIGNING_KEY: ${{ secrets.GIT_SIGNING_KEY }}
